# Project information
site_name: Naruto Senki - V2 Documentation
site_author: Re
site_url: https://docs.naruto.re/
edit_uri: https://github.com/naruto-senki/docs/edit/main/docs/

# Deployment
remote_name: origin
remote_branch: gh-pages

# Repository
repo_name: naruto-senki/docs
repo_url: https://github.com/naruto-senki/docs

# Copyright
copyright: Copyright &copy; 2022 Re

theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/favicon.png
  icon:
    logo: logo
  pymdownx:
    sponsor: "https://docs.naruto.re/about/sponsor"

# Customization
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://game.naruto.re
    - icon: fontawesome/brands/github
      link: https://github.com/naruto-senki
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCL9gDeedGZdf3hjRd-Zr7cg
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/122989580

extra_css:
  - assets/css/extra.css
  - assets/css/hint.min.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  # - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav: # NOTE: i18n doesn't replace nav's title in default language with multiple topics
  - index.md
  - 游戏指南:
      - game-guides/index.md
      - game-guides/platform/mobile/index.md
      - game-guides/platform/pc/index.md
  - 问题汇总:
      - issues/index.md
      - issues/faq/index.md
  - changelog/index.md
  - 关于:
      - about/index.md
      - about/sponsor/index.md
      - about/team/index.md
      - about/supported-platforms/index.md

i18n:
  zh:
    site_description: 快速了解游戏玩法及更多信息。
    theme: # TODO
      - light_btn: 切换至夜间模式
      - dark_btn: 切换至日间模式
    home:
      title: "火影战记: V2的简体中文技术文档"
      start_btn: 快速开始
      sponsor_btn: 成为赞助者
    issue:
      total: 总数
      success: 已解决
      bug: BUG
      question: 其他问题
      failure: 崩溃
      unknown: 未知
  en:
    site_description: Get a quick overview of gameplay and more.
    theme:
      - light_btn: Switch to dark mode
      - dark_btn: Switch to light mode
    home:
      title: "Technical Documentation for Naruto Senki: V2"
      start_btn: Quick start
      sponsor_btn: Become a sponsor
    issue:
      total: Total
      success: Done
      bug: BUG
      question: Question
      failure: Crash
      unknown: Unknown

# Plugins
plugins:
  - i18n:
      default_language: zh
      languages:
        zh:
          name: 简体中文
          site_name: 火影战记 - V2 文档
        en:
          name: English
          site_name: Naruto Senki - V2 Documentation
      material_alternate: true
      nav_translations:
        en:
          游戏指南: Game Guides
          问题汇总: Issues
          关于: About

  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: false
      exclude:
        - index*.md
        - assets/*
      fallback_to_build_date: true
      enabled: true
  - search:
      lang:
        - en
        - ja
        - zh
  - tags
  - tooltips
  - minify:
      minify_html: true
      # minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_all_empty_space: true
        reduce_boolean_attributes: true
        remove_optional_attribute_quotes: true
      # js_files:
      #   -
      css_files:
        - assets/css/extra.css
